INSERT INTO FRUIT (ID, UUID, NAME, PRICE) VALUES(1,'d3f8','신고산 배',1000);
INSERT INTO FRUIT (ID, UUID, NAME, PRICE) VALUES(2,'23gk','나주 배', 800);
INSERT INTO FRUIT (ID, UUID, NAME, PRICE) VALUES(3,'349t','영덕 사과', 900);
INSERT INTO FRUIT (ID, UUID, NAME, PRICE) VALUES(4,'f7pk','경주 사과', 1100);
